### ISSUE TITLE
Level 7 Wizard Spells Disabled by Grimoire Mod

### ISSUE THREAD

**Issue by tjayharvey** [GregRos/IEMod.pw#12]
With Grimoire Bonus Mod installed (whether turned on or not), wizard spells level 7 was greyed out and unselectable. This turned out to be some additional "magic number" 6s that hadn't yet been incremented. I have a commit that increases them to 8, following your lead with other sections of that file. I will send a pull request at some point.

**Comment by GregRos** [comment]
Cool. I'll try to refactor those to consts.

**Comment by GregRos** [comment]
Okay. Done. It seems to work. I also replaced the 4s with `MaxSpellsPerLevel` and removed the modification of that const that was there, since it does absolutely nothing.

**Comment by tjayharvey** [comment]
Confirmed that it works. Closing issue
