### ISSUE TITLE
Determine what to do with Fast Sneak's mod_PathingController

### ISSUE THREAD

**Issue by tjayharvey** [GregRos/IEMod.pw#16]
I can't figure out why this is here and it doesn't seem to be needed, but it would be good to have a second opinion.

**Comment by GregRos** [comment]
Yeah, it seems to be related to toggle walking mode. I just misfiled it while organizing the old content. I'll try to organize it correctly.

**Comment by GregRos** [comment]
I'm going to close this issue, along with a few others, because they're all related to ToggleWalking, so I'll create a new issue for that.
