### ISSUE TITLE
Per Encounter Spells - What Options with level 14?

### ISSUE THREAD

**Issue by tjayharvey** [GregRos/IEMod.pw#18]
Old Options                       New Options
Normal (9, 11)     ------ >    (9, 11, 13)
9, 12
6, 9, 12
6, 8, 10, 12         -------> 6, 8, 10, 12, 14?
4, 6, 8, 10, 12     -------> 4, 6, 8, 10, 12, 14?

Do you agree with the last two? What would you do with the other two? I'm happy to make this work up to level 14, just not 100% sure what to do with those options. The pattern would leave them unchanged, but it seems weird that 9, 12 would be the only option that doesn't get level 3 spells per-encounter (but then, I guess someone who thought that adding level 3 spells would add even more power to already powerful casters might not want it).

**Comment by GregRos** [comment]
Personally I think I might use the 9, 12 option myself, so I'd rather it would remain like that. I kind of think level 3 add even more power to already powerful casters lol.

For the other options, I think we should continue the pattern.

**Comment by tjayharvey** [comment]
Final set of options: 
Normal (9, 11, 13)
9, 12
6, 9, 12,
8, 10, 12, 14 (new)
6, 9, 12, 14 (new)
6, 8, 10, 12, 14
4, 6, 8, 10, 12, 14

I added two options, since none of the existing options (with the last two extrapolated to level 14) gave the option to have level 4 spells but not level 5 go encounter only. 

Still testing it before committing. 

I will probably use 6,9,12 or 6,9,12,14. I don't like the concept of classes that don't acquire much of their power until late (or the reverse, really - powerful early classes that don't scale well). But then, I may have played too many MMOs.

**Comment by tjayharvey** [comment]
The UI was not reporting the correct information about encounter levels on level up (it was always using the "normal" spell levels). I believe I have this fixed. Just takes a while to test all these options.

**Comment by tjayharvey** [comment]
Testing complete. Closing this issue.
