### ISSUE TITLE
UI Customization Mod affecting NPC tooltips

### ISSUE THREAD

**Issue by tjayharvey** [GregRos/IEMod.pw#19]
With UI Customization Mod included, but not turned on, I was observing many NPC's tooltips (when holding Tab) disappeared. Most of the time they were gone, but occasionally they would be present. I also don't have One Tooltip At a Time checked. Commenting out mod_UITooltip and mod_UITooltipManager may have fixed the problem (but because this is intermittent, I will report back after more playtime).

**Comment by GregRos** [comment]
That's weird. I don't have this problem. Are you using the latest version 2b64b4324e11014c9602972b0e5d90300abfb62c, after the merging I did? I integrated some changes about tooltip visibility.

Also, I think I made a mistake putting those classes in the UI Customization folder, because they're not really related. They don't seem to depend on the `CustomUI` option.

**Comment by tjayharvey** [comment]
This was tested in the previous version. I'm trying to test it now, but when I merged your changes down it doesn't compile. Something about a class called BodyFileChange that it can't identify. Where is this class supposed to be? Did I mess up the merge somehow?

**Comment by GregRos** [comment]
You need to pull Pathwork down again

**Comment by tjayharvey** [comment]
Gah. I can see that Git gives you a lot more options, but man is it fiddly in places. I would have thought pulling the change to IEMod.pw that changed the version of patchwork would have been sufficient.

Seems to work now. I will leave it open until I play a few hours and make sure it isn't still there and just not showing me right now.

**Comment by GregRos** [comment]
You get used to it :) It can do some pretty amazing things.

**Comment by GregRos** [comment]
I've been playing quite a bit, and I haven't seen this reappear. Should we close it?

**Comment by tjayharvey** [comment]
Sure
