### ISSUE TITLE
UI customization interface appears darker and doesn't function sometimes

### ISSUE THREAD

**Issue by GregRos** [GregRos/IEMod.pw#20]
Yeah, it was too early to say it was working properly. It doesn't always work. Sometimes when you click the `Customize UI` button, the customization interface appears darker than normal and doesn't function, or only some of it does. 

Can you keep an eye on it to see if it's not just on my machine?

**Comment by tjayharvey** [comment]
I'm not entirely certain how this is supposed to work (haven't played with this one in prior versions). But I agree it looks broken. Here's a screenshot of what my screen looks like after an area transition:

![2015-08-29_00001](https://cloud.githubusercontent.com/assets/13974045/9564537/3d39e370-4e5f-11e5-84bf-ff5e1e823b89.jpg)

**Comment by GregRos** [comment]
LOL yes it does definitely look broken. Mine isn't like that. Could you post your logs?

**Comment by GregRos** [comment]
Actually nevermind. The reason is pretty obvious. I'll upload a fix. Dunno what I'd do if it was just me lol

**Comment by GregRos** [comment]
I fixed it, but it may have caused other bugs, so I'm going to play with it a while. I did push it, but not to the master branch, but to another branch called `CustomUIFix`. You can pretend it doesn't exist. I'll eventually merge the work into the master.

**Comment by GregRos** [comment]
Okay, I merged the changes into master. I really think it should be fine now. You will probably have to type the following command into the console though, after a level has been loaded: `ResetCustomUI`, and then exit to main menu. This is only because the mod saved invalid UI settings; users won't have to do it.

I also haven't seen the original problem appear (that I had on my machine). I hope that what I did fixed it as well.

**Comment by tjayharvey** [comment]
Well, it's better. I'm not sure if the drag buttons are supposed to display in the middle of the screen like this. And the textures of the bottom center buttons definitely look messed up.

![2015-08-30_00001](https://cloud.githubusercontent.com/assets/13974045/9568462/b5e4f662-4efe-11e5-9639-9259ff0c09f5.jpg)

**Comment by GregRos** [comment]
Yes, the buttons are supposed to display in the middle of the screen. For now anyway.

I have no idea at all what causes the texture problem :( I can't seem to reproduce it. Does clicking the `T. Custom Textures` button do anything?

Also, do you have the IEMod assets folder installed?

**Comment by tjayharvey** [comment]
Yeah, that was it. I had them installed, but hadn't updated since the original version. I pulled the 1.0.6  version and it seems to be behaving itself now.

**Comment by GregRos** [comment]
Haven't encountered this problem anymore, so closing this.
