### ISSUE TITLE
I'm giving you pushing permissions

### ISSUE THREAD

**Issue by GregRos** [GregRos/IEMod.pw#21]
So you can push to this repo. It's best if one person does the pushing, but you can also push if I become unavailable or something. You shouldn't worry about losing data, as it's very difficult to lose data on git. Just don't do anything that says _force push_ on it, unless you're sure.

I think this also allows you to edit my issues/comments, but maybe you have that ability already. 

Do you have a nexus account? I think I can also give you permissions on the IE Mod page there.

**Comment by tjayharvey** [comment]
Don't think I have one, but I can add one.

Do you want me to push the FastSneak change? Or are you working on integrating that?

**Comment by GregRos** [comment]
I'd rather you submit pull request and I merge them for now, except when I'm away. It's just better when one person does the pushing, at least until we get a better handle on how to merge changes.

Yes, I'm working on merging your pull request :)

**Comment by tjayharvey** [comment]
Yeah, I definitely feel more comfortable with you doing the merging. Would rather not create any problems :)

**Comment by GregRos** [comment]
Oh and yes make the nexus user. The more people have access to the page the better, in fact (within reason). I barely managed to get hold of permissions this time.

**Comment by tjayharvey** [comment]
I had one, I had just forgotten about it. tjayharvey there as well.

**Comment by GregRos** [comment]
Can you give me the user number? You can see it when you log into your account, like:
    `http://forums.nexusmods.com/index.php?/user/5343713-springwight/`

**Comment by tjayharvey** [comment]
103067 seems like it might be it?

**Comment by GregRos** [comment]
Okay, I think it should work. Try to see if you can edit something. Here is the page: http://www.nexusmods.com/pillarsofeternity/mods/1/?

**Comment by tjayharvey** [comment]
I have an Admin panel and editing the description appears to work (I didn't actually save any changes).

**Comment by GregRos** [comment]
Great :) Closing issue.
