### ISSUE TITLE
Something in IEMod causing Iconic Projection to consume multiple spell slots.

### ISSUE THREAD

**Issue by tjayharvey** [GregRos/IEMod.pw#23]
I noticed this while testing per encounter spells, but I can reproduce it with that mod off and that mod commented out, so it's not related. It also doesn't appear to occur in the base game. I left the party in two per line formation, moved Durance in line about half a screen away, and cast Iconic Projection on the party. The number of level 2 slots it used up varied, but was usually at least 2 (I saw all 4 go in one test). 

I had Target Turned Enemies and Disable Friendly Fire both off.

**Comment by GregRos** [comment]
I think I fixed it in my 2nd round of merging. It was related to some stale code form previous versions.

**Comment by tjayharvey** [comment]
Looks fixed now.
