### ISSUE TITLE
Small bits of code that need to be integrated manually

### ISSUE THREAD

**Issue by GregRos** [GregRos/IEMod.pw#24]
In my latest round of merges I integrated most of the remaining code. There are some bits that need to be integrated manually though. Or maybe some can be discarded. There are `//TODO`s where it needs to be done.
Let's say these are yours:
- [x] `mod_UIOptionsManager.StartNew`
- [x] `mod_UIConsole.AdjustBackgroundNew`
- [x] `IEMod.Mods.PartyBar.mod_UIPartyPortraitBar`

And these are mine:
- [x] `IEMod.Mods.Tooltips.mod_UIMapTooltip`: I didn't fully fix it. The code is complex (involving a lot of math, with lots of magic numbers), and I decided trying to understand it was too much work. We may have to return to it if it starts acting up. 
- [x] `Mod_CombatLooting_Container`
- [x] `Mod_CombatLooting_UIIventoryGridItem`

**Comment by tjayharvey** [comment]
Sure, works for me. I'll try to start on these tonight.

I will also take checking out the other spell mods to make sure they work correctly up to 14.

**Comment by GregRos** [comment]
Oh. There is a problem with this process, when trying to merge constructors. The thing is, in the IL field initializers are just statements in the instance or static constructor. Decompilers intelligently decompile those statements into initializers, and you can't turn this option off. But you still need to insert them if you're modifying the body of a constructor, since Patchwork can't detect which statements are initializers, and which aren't. So when trying to merge statements from the new constructor, you have to either:
1. Manually put every initializer into the modified constructor body.
2. Call the original constructor using `DuplicatesBody`. This isn't always possible, though it usually is.

Actually, the decompiler I used for merging does not decompile initializers (it just leaves them as statements in the constructor), so it's perfect for this kind of work. You can try to decompile a constructor using this custom decompiler by calling `ModifiedDecompiler.Decompile` in the `_Start` project (do not call ReplaceCodeWithOriginal as it modifies your source code).

**Comment by tjayharvey** [comment]
Sorry, got delayed trying to understand how attacks work (bounces and extra AOEs and everything). Didn't expect to spend so many hours down the rabbit hole. I will try to get to this tomorrow afternoon.

**Comment by GregRos** [comment]
Take your time :) We're make far better progress than I expected.

**Comment by tjayharvey** [comment]
I can't tell what mod_UIConsole.AdjustBackgroundNew was trying to accomplish. It looks like they rewrote part of the transform logic. Regardless, the original function didn't change from 1.06 to 2.0, so I think it's safe to ignore it?

The PartyBar, while I can understand what it's trying to do, also hasn't had the original changed from 1.06 to 2.0. Are there any symptoms of it not working correctly?

**Comment by GregRos** [comment]
@tjayharvey These are just bits of code I couldn't merge with the diff tools, because the text was too different or something. If it doesn't need any modifications, then everything is okay.

**Comment by tjayharvey** [comment]
Done with mine, I think.

**Comment by GregRos** [comment]
Great. Closing.
