### ISSUE TITLE
The issue with PathConsts.DoNotPush

### ISSUE THREAD

**Issue by GregRos** [GregRos/IEMod.pw#26]
It seems that doing what I wanted with this file (upload it to the repo once, and then make git stop tracking changes to the file, so anyone can edit it freely) is impossible to do automatically. There are two options:
1. Each person will have to execute the command `git update-index --assume-unchanged PathConsts.DoNotPush.cs` on their git shell (I think it can be accessed from any git client)
2. There will be a `PathConsts.Default.cs` file, and each user will have to copy it to `PathConsts.cs`, which will be ignored (this file will be referenced by the csproj file).

What do you think?

**Comment by tjayharvey** [comment]
Either works.

I'd almost like to convert this to an app.config so we can all have our own transforms without stepping on each other, but not a priority at the moment.

**Comment by GregRos** [comment]
In that case, lets just execute the command, since it involves less messing about, and do something more thorough later. I already executed it on my end. 

When you pull the first time, you might have to discard some changes to the file, but after that it should be smooth sailing. Check to see if anything you do makes the file appear modified, just in case.

**Comment by GregRos** [comment]
There was no change with the file in the last merge. Hopefully the issue will no longer come up.

**Comment by GregRos** [comment]
So the other day I had to
