### ISSUE TITLE
Anything else we should do before we release something?

### ISSUE THREAD

**Issue by GregRos** [GregRos/IEMod.pw#30]
Can you think of anything like that?

**Comment by tjayharvey** [comment]
Feels to me like we have enough of the functionality restored for a beta release, as long as we communicate that we don't have a QA staff and haven't exhaustively tested anything.

I think there's enough that people do want (console, walk mode, UI customization, etc) that seems to work right that they'd be happier getting some pieces available and working even if we do end up with a few outstanding issues.

**Comment by GregRos** [comment]
Alright. I'm gonna try to get the dll files for the linux and mac versions to see if they're any different.

I'm quite certain that the changes we need to do are the same, but the binaries may differ in some way.

**Comment by GregRos** [comment]
Okay, I'm going to release what we have for Windows, and ask people to give us their `Assembly-CSharp.dll` for Linux and Mac if they want a version for those (or alternatively just risk it and use our dll).

A few last things. What name and version should we use? Where should users post bug reports? What should we ask of users when they post them?

**Comment by tjayharvey** [comment]
No real preference on the name/versioning. I think we'll probably see some bugs reported in many places and we'll have to collate them here. For content, I'd hope for a full description, whether it's Windows/Linux/Mac, and... I don't know really. For complicated bugs we might want a saved game to play with.

**Comment by GregRos** [comment]
Okay, I've put the release at 5.0.0-beta, and removed the 'pw' from the version, since this is the main version now. I won't rename the repo though because I've already put links to it in various places.

I uploaded a release onto here. Can you check if it runs on your computer to avoid those "oops" moments? It's in the releases folder.

**Comment by GregRos** [comment]
Oh, we forgot to address compatibility with/without White March... do you have it? (I do)

**Comment by tjayharvey** [comment]
I do as well. No idea what's different about the game with one or the other. My guess is probably nothing in the DLL, but we might have to find someone to test for us.

**Comment by GregRos** [comment]
Hey, if you get around to testing it, could you release it on nexus? 

I gotta go to bed. Good night

**Comment by tjayharvey** [comment]
Er, sorry. Had completely missed the "release to test" in this thread. I'll see what I can do with it.

Edit: I'm not actually seeing it? All I see are the two releases from 19 days ago?

**Comment by GregRos** [comment]
I had put it in an actual folder in the repo, but then I realized this is counter-productive, as everyone who pulls it will also pull a copy, which is totally unnecessary. Now I uploaded it as a GitHub release.

I'll just release and we'll see how it goes.

**Comment by GregRos** [comment]
Okay, I released it.

And yeah, and the windows and linux binaries are different... it may be that the ±White March binaries are different. I think I need to write an end-user patching system for patchwork, so anyone can update their DLLs. Do you have any thoughts on this subject?

**Comment by tjayharvey** [comment]
I think it's a really good idea and I was going to suggest it at some point anyway after we got stable.

If anyone ever DOES do mods beyond IEMod, it would be really useful to have those be delivered as PatchingAssemblies and the end user patches them into their system, rather than have the developers do compatibility patches.

**Comment by tjayharvey** [comment]
I put release notes on the forum thread (mostly cribbed from the project read-me, rewritten to be a little more formal PoV), including our current known issues.

**Comment by GregRos** [comment]
Well, it's settled. WM doesn't change the DLLs.

**Comment by tjayharvey** [comment]
Great! Less versions to maintain.

**Comment by tjayharvey** [comment]
Since we've released several times, seems like this should be closed.
