### ISSUE TITLE
Patching system for multiple DLLs, additional versions

### ISSUE THREAD

**Issue by GregRos** [GregRos/IEMod.pw#33]
We need some code to patch multiple DLLs (for different versions), and also upload the DLLs for the other OSs (we got a MAC dll so far). It will take a while to get the end-user patching system going, so we should at least have that. It doesn't seem like the White March DLLs are different.

Could you handle it? Just assign yourself if you feel like it.

**Comment by tjayharvey** [comment]
I will try. However, a crisis has come up at work and I'm not sure how much time I will have in the next couple of days. I will assign it to myself when I start working on it.

**Comment by GregRos** [comment]
Ah that's alright :) then I'll just work on it.

Good luck.
