### ISSUE TITLE
The "BSC" console command is not recognized.

### ISSUE THREAD

**Issue by Bigtuna00** [GregRos/IEMod.pw#34]
With IMod Version 5.0.0-beta for Windows 2.0.0706 PX1, the "BSC" console command is not working. The message is "No command or script 'BSC' accepting 2 parameters exists."

**Comment by GregRos** [comment]
Do you want us to change the name to something descriptive, or is "BSC" fine with you?

In previous versions, did hostile summoned creatures attack? If so, there is a more serious bug here.

**Comment by Bigtuna00** [comment]
I do think the name is a bit odd but as long as it's documented it doesn't really matter to me. 

It's been too long since I've used the command but I'm pretty sure hostile creatures would attack and also that npcs would attack them. I have a vague recollection of spawning creatures in Caed Nua and seeing my guards attack them. If you want I can try to figure out how to install the old version and try it.

**Comment by GregRos** [comment]
Nah, that sounds like too much of a bother.

In the latest development build, the creature appears, but doesn't have an AI. It can be hostile or friendly, and others react to it correctly, but the creature does nothing. 

It may be because creature AI has been changed a lot, and now we need to add another AI component or something. Or maybe that's how it was like before. I'll try to look into it anyway.

**Comment by Bigtuna00** [comment]
I see what you mean.  For my purposes I'd be ok with it not attacking...lol. Since my party is/was at endgame before the White March it's pretty much impossible for me to level some of the Soulbound items since there's not enough content.  But I suppose in the long run they should have some AI as well :)  Thanks for working on it.

**Comment by GregRos** [comment]
The command is back in [v5.0.2-beta](../releases) (or you can get it off nexus).

**Comment by Bigtuna00** [comment]
Looks like an update for POE was just released on Steam. The new version is 2.01.0721. I've installed v5.0.2-beta but none of my save games will load; I assume that's why. Will test the fix as soon as I can.

**Comment by Bigtuna00** [comment]
I was able to build locally and test BSC. It's working insomuch as I can spawn hostile NPC's and they attack. Unfortunately I can only summon _1_ of each.  After summoning and killing the NPC, further attempts to summon it appear to fail because it's already in the world but dead.  I don't actually know if that's a bug or not?  There's probably a way to delete the NPC and summon again, or just move to another area and wait for the corpse the despawn.

**Comment by GregRos** [comment]
@Bigtuna00 That's almost certainly a problem that existed before. 

It looks like fixing the command is pretty complicated. It's not that it requires a lot of deep thought or ingenuity, it just requires time to test various things, and see if they work (or knowledge of typical Unity game design). For example, I could try to clone the creature, but I'd probably have to give it some set of unique identifiers for that to work properly, and finding out what exactly the game needs would take time.

I could just give you a console command to level soul-bound gear. That's probably a lot simpler.

**Comment by Bigtuna00** [comment]
Hah good point.  I was able to level my gear actually without too much hassle. It was a matter of finding enough unique NPC's and then moving to one new area.  So I'm good there.  Thanks for your efforts!
