### ISSUE TITLE
Visiting the Options screen with "Automatically Save Changes" unchecked gets you stuck in a "Save Changes" prompt loop

### ISSUE THREAD

**Issue by tjayharvey** [GregRos/IEMod.pw#4]
Type: In-game bug

Repro steps: 
1) Load a game 
2) Visit the Options Screen
3) Make sure "Automatically Save Changes" is unchecked.
4) Click the "Save Game" option
5) Note the prompt to save the changes. Clicking either yes or no will just repeat the same window/leave it open. 

Analysis: 
Appears to be caused by GameMode.Matches returning false even after saving. This method is "patched" in IEMod/Options/mod_GameMode. Testing shows that IEModOptions.IsIdenticalToPrefs() always returns false. Further investigation highlighted the IEModOptions.LayoutOptions as always failing its comparison. Appeared to be due to the LayoutOptions class missing an appropriate Equals method. Adding an Equals override testing each of the member variables for equality appears to have fixed the issue. This fix has been checked in and is in my current pull request.

Root Cause Analysis:
Difficult to understand why the 2.0 patch should have caused this to break. The only thing I can think of is that the game was not checking after saving in prior versions to make sure GameMode.Matches() was now true.

**Comment by GregRos** [comment]
Sweet :) Good find.
