### ISSUE TITLE
My managed folder may be screwed :/

### ISSUE THREAD

**Issue by GregRos** [GregRos/IEMod.pw#42]
I smessed up my managed folder (with the new update) by mistake. Can someone upload theirs? I need the entire thing, just to be on the safe side.

**Comment by tjayharvey** [comment]
How do you want it? Won't let me attach the zip directly (too big).
Nice thing about Steam is I can just verify files and it cleans up everything that I might have messed up.

**Comment by GregRos** [comment]
Dunno. you can email me at `life.gregr@gmail.com`. or dropbox link.

**Comment by GregRos** [comment]
Well, this is interesting. I'm not sure how or why, but the game won't work even after I replaced the Managed folder. Which is pretty weird, because that's the only thing I messed with. Maybe when I ran the game like that, it somehow corrupted something else. At least new game doesn't work either, so it's not the save. 

It's also possible this is just because of the patch. Too many variables.

I guess It's time for a re-install. 

If you have time, could you test out the latest version and release?

**Comment by tjayharvey** [comment]
Seems to work all right to me.

Did you update your binary in the PoE Dll Source/win folder? Prepare Environment currently won't do that for you and I don't remember if I committed mine. Though, if that was the case, you should have gotten a PEVerify error (which was how I noticed it originally).

**Comment by tjayharvey** [comment]
How do you do the release? Just zip up the dll + the assets?

**Comment by GregRos** [comment]
Ohhh good point. If you've made the changes, can you commit them? (you might have to merge with some of the refactoring I did)

We also don't have linux/mac DLLs for the new version. Asking people for theirs isn't very effective. I guess that's all there is right now. 

As for the release, yup, that's it. 

Ahhh yeah I think there's a good chance that mixup with the DLL somehow screwed up my game files. That's the only thing I can think of at least.

**Comment by tjayharvey** [comment]
Think I've merged everything Git thinks I've changed, so it should have been in my previous pull request you've already merged. Not sure if it picked up the change the binary. 

I have incremented the version number. I will merge that up in a bit.

**Comment by tjayharvey** [comment]
New version is up. I think.

**Comment by GregRos** [comment]
Sweet :)

My issue is fixed. In fact, I hadn't actually corrupted my Managed folder, I was just being an idiot. Sorry to have bothered you. :disappointed:
