### ISSUE TITLE
IEMod Version 5.0.4 Release

### ISSUE THREAD

**Issue by GregRos** [GregRos/IEMod.pw#48]
It looks like all we have are small bugs. I doubt any more major patches will be coming out anytime soon, so we might as well drop the beta label. 

Any thoughts?

**Comment by tjayharvey** [comment]
Seems okay. With the number of mods we have, and the scope of some of them (no friendly fire, UI), users should not be overly critical of smaller bugs remaining.

I went with the beta label partly because I wasn't entirely sure if I was doing the release properly, so I wasn't sure if it would work.

**Comment by tjayharvey** [comment]
I'd recommend we plan to do a release soon and take the beta label off. This would incorporate:
- Healing fixes to Friendly Fire (already merged, not released).
- Bugfix for caster-targeted spells (already merged, not released)
- Combat Triage fix (already merged, in testing)
- Soulbound Weapon Levelling console command (awaiting merge)
- Initial ability replacement mod (awaiting merge).
- Max Adventurers Count Mod (awaiting merge)

That would also let us get a version out for 2.01 for Mac/Linux, which I don't think there currently is.

When do you think you would be able to have TargetTurnedEnemies fixed? 
Do you want to do the release or do you want me to?

**Comment by GregRos** [comment]
I'm still trying to get my bearings, unfortunately. I also want to release soon, though.

I should push a fix to TargetTurnedEnemies tomorrow. There are also various bug reports in the nexus that I want to squash. 

Not sure about Max Adventurers mod.

It doesn't matter to me who does the release. Whoever has time and feels it's ready enough.

**Comment by tjayharvey** [comment]
I've marked the Combat Triage and Friendly Fire Healing bugs on the Nexus as fixed in the next build. Will close them when we release.

Which other bugs do you want to tackle from the Nexus list?

**Comment by GregRos** [comment]
I wanted to look into that issue with Cilant Lis and the Disposition thing. I also wanted to test the adventurers mod.
.

**Comment by GregRos** [comment]
The adventurers mod seems to work. 

I don't know how to test the disposition mod (I'm not 100% sure what it does lol). 

I'm testing the issue with Celiant Lis right now (started a new game to do it). The reported issue may have been caused by the targeting mods, in which case I shouldn't experience any problems.

**Comment by tjayharvey** [comment]
I've just tested the disposition mod and it definitely works for hired adventurers. Basically, paladin and priest orders affect their Faith and Conviction and Holy Radiance abilities respectively, but in the unmodded game, only for the Main Character. Ticking the checkbox makes it apply to other people. I had a reputation of 2 Benevolent and 2 Passionate and hired a Kind Wayfarer, and instead of 5/10 Defenses it was 8/16 (probably because the reputations aren't integers - if I had 1.6 and 1.6, that shows as 2 but summed, rounds to 3). Similarly, with 1 Clever and 2 Passionate (net -1), Durance's Holy Radiance dropped from healing 18 a tick to healing 15 a tick.

**Comment by tjayharvey** [comment]
It works for Pallegina too, but in her case you have to select what Dispositions are favored and disfavored by her order, since the base game doesn't include any.

So I'm going to reply asking for more information, because it looks like it's working fine to me.

**Comment by GregRos** [comment]
I'm working on solving the Celiant Lis problem. It's coming from the targeting mods again. God I HATE `NullReferenceException`s. :(

**Comment by tjayharvey** [comment]
NPC Disposition Issue marked as Need More Information on Nexus. I'd suggest we not wait for it since we do have some bugfixes that would be good to get out (especially the Friendly Fire healing one, which makes that particular mod pretty hard to use), and it appears to be working fine for me.

**Comment by tjayharvey** [comment]
I've also had someone that wants us to add the Black and Gold buttons file back in and sent me the necessary file. Do we have somewhere in the repo we are keeping those resources for the UI?

**Comment by GregRos** [comment]
Yeah, it's in the `IEMod\iemod` folder.

**Comment by tjayharvey** [comment]
Deferred Black and Gold to next release. Have gone ahead and released this as 5.0.4
