### ISSUE TITLE
Target Turned Enemies Mod Not Updated for 2.0 (breaks Field Triage)

### ISSUE THREAD

**Issue by tjayharvey** [GregRos/IEMod.pw#52]
If you haven't already fixed this I will take a look at it this evening.

**Comment by GregRos** [comment]
Nope, haven't fixed it. Thanks! :)

**Comment by tjayharvey** [comment]
Verified problem exists. Cannot currently build due to missing file in patchwork (and not sure how to roll that back). Will continue when I can build again.

**Comment by tjayharvey** [comment]
Figured out how to roll Patchwork back (and thankfully I had a branch where IEMod wasn't up to date, so I can build okay with it). 

Here's the rundown: The problem is in the Targeting mod, in mod_AttackBase. Field Triage requires a target of type FriendlyNotVessel, which isn't even in the modded version's switch statement. It looks like this entire function was never updated to patch 2.0, which appears to have substantially refactored this including a whole host of variable name changes. I was able to fix it by copying the 2.01 code for FriendlyNotVessel and modifying for the old variable names, but it might be a better idea to just fix this by pulling the 2.01 version and reapplying the mod's change over the top of that. I can probably do that, but since it's your mod (TargetTurnedEnemies) that needs to be refreshed, it might be better for you to tackle it, since you understand more of how it's supposed to work.

**Comment by tjayharvey** [comment]
It also appears this mod never worked with target types HostileWithGrimoire, HostileVessel, and HostileBeast (not that it broke, but it didn't implement the "charmed are still hostile" effect). This is probably not very interesting for HostileWithGrimoire (probably only the lame Grimoire imprint spell) and I'm not sure there any Beast-only abilities outside of Charm Beast (which isn't very useful on a charmed beast!), but I'd expect there are some HostileVessel abilities that might be nice to use against a charmed target.

**Comment by GregRos** [comment]
Have no idea how I missed it. I definitely remember porting something related to it. I ported so many tiny things, I can't believe I missed a whopper like that one.

I'll take care of it.

By the way, using git, you can go back to any commit you like just by checking it out. It will restore all your files to the state they were at the time of the commit. So even if the latest commit is broken, you can go back in time to anywhere you want. It's like magic.

[Here is an example of it](http://i.imgur.com/VCBqaE1.png) in SmartGit

**Comment by GregRos** [comment]
I'm trying out a somewhat different fix that significantly reduces the invasiveness of the targeting mods. It's something really simple but gets rid of most of the code. I'm gonna play with it for a while and experiment, to see if everything works correctly.

**Comment by GregRos** [comment]
Okay. It's a really bad idea to mess with this code. The number of exceptional cases is just way too big. Targeting is implemented in a really messy way. 

I'm testing various combinations of options in different situations.

**Comment by tjayharvey** [comment]
My initial attempt to fix it described above, which basically consisted of just adding a clause to handle FriendlyNotVessel, somehow caused autoattacking to break. So yeah, I agree it's kind of a mess. If you need any testing help I'm happy to pitch in.

**Comment by GregRos** [comment]
Yeah when I'm done with it I'd be thankful if you give it a go too.

**Comment by GregRos** [comment]
Okay, I hope it works now. Can you try it out on your end?

You might have to merge some of the changes I made with Patchwork. Though they're not really related.

**Comment by tjayharvey** [comment]
Confirmed Field Triage works, and that healing under Friendly Fire still works (previous fix). Will play with it tonight and let you know how it goes.

**Comment by GregRos** [comment]
I think I've fixed the Celiant Lis issue. There is this weird thing where when the trap is sprung, it keeps spamming this to the log:

```
Look rotation viewing vector is zero
(Filename:  Line: 70)

Look rotation viewing vector is zero
(Filename:  Line: 70)

Look rotation viewing vector is zero....
......
```

Disk IO being what it is, it causes a pretty big performance hit. However, this probably happens in vanilla as well.

I'm gonna test it in case I introduced another bug (it feels a bit like playing whack-a-mole).

**Comment by GregRos** [comment]
Okay, I've pushed the fix. However, I haven't tested how things work with dominated/confused party members, because I don't have any save near creatures that can do this.

**Comment by tjayharvey** [comment]
What's a good creature to test with?

**Comment by tjayharvey** [comment]
2.0 issue. Closing
