### ISSUE TITLE
Type reference issue?

### ISSUE THREAD

**Issue by Empyrial** [GregRos/IEMod.pw#54]
I'm a newbie, so I probably missed something, but I'm getting an error when running the _Start! method:
<code>Could not resolve a type reference, most likely because it wasn't imported. Details: <PrivateImplementationDetails><IEMod.dll></code>
I did the pre-environment setup, had to fix some references, and change a setting for patchwork to build debug binaries by default, but I got the main package compiling.  Through reflection, I found PrivateImplementationDetails in the CSharp assembly code, but I don't understand where the type is failing?

**Comment by GregRos** [comment]
What IDE are you using?

**Comment by Empyrial** [comment]
vs 2015 community

**Comment by GregRos** [comment]
I'm not sure what could be causing this issue. Could you upload your `IEMod.dll` from your latest build?

Also, is there a chance the base DLL you're using is _not_ the original one, but a modded one? Or that `Paths.YourOriginalManagedFolder` contains modded DLLs?

**Comment by Empyrial** [comment]
The IEmod is built from the project base.  [Download IEMod.Dll Here](https://www.dropbox.com/s/q44koaftke0fxmt/IEMod.dll?dl=0).  No, I'm using the one from my GoG folder, and not a modded one.  I double-checked and confirmed versions and file sizes.  

I thought I'd add some more info, in case it helps - 
![debug](https://cloud.githubusercontent.com/assets/13545752/9801483/544e4b24-57e1-11e5-9e59-40d06d31618c.png)

The throw is after attempting to create the last type there.  It throws after the instruction to create a new TypeDef in the CreateNew of Patchwork.  

I'm thinking I might have screwed up patchwork somehow?  I guess it just seems to me that this is generic enough to not be a compilation issue.  Perhaps that is naive of me.

**Comment by GregRos** [comment]
Could you upload that DLL? I'm quite certain the problem is somehow related to it, so it would help a lot. I'm guessing that your compiler somehow generates different output from mine, and PW can't deal with it.

If you think you screwed up PW, just download/pull it again.

**Comment by Empyrial** [comment]
Ok, I added the link to my dropbox with it to the previous post.  I'll add it again here - https://www.dropbox.com/s/q44koaftke0fxmt/IEMod.dll?dl=0.

I rebuilt patchwork a second time from source, and still the same, so I'm not sure anymore about that.

**Comment by GregRos** [comment]
Yes, like I suspected, your compiler compiled the assembly differently from mine, and it tripped a bug in `Mono.Cecil` (which is a library Patchwork uses under the hood). 

Do you have any idea what makes your compiler different from other compilers? I never had this problem before, and it's probably uncommon, or else `Mono.Cecil` would've fixed it in the past.

The problem is caused by your compiler naming a compiler-generated type `<PrivateImplementationDetails><IEMod.dll>`, where up until now the type was called `<PrivateImplementationDetails>`.

Since we have the source code, I'll just fix the bug here, and also post an issue over there.

**Comment by Empyrial** [comment]
I have no clue why anything of mine would be different.  It is all standard installs.  Nevertheless, very interesting stuff.  I'll research, and see if I can do anything about it.  Thanks for the fast responses.

**Comment by Empyrial** [comment]
For reference, the csc version I'm using is 1.0.0.50411.

I'm looking into why the object name would be appended to PrivateImplementationDetails, and I'll see if maybe the mono compiler might change the assembly...

**Comment by GregRos** [comment]
Okay try the latest commit (afa1fdfa6762991dd94f6a6cbbabbb120f7755d6). It should fix the problem.

**Comment by Empyrial** [comment]
Yes, that fixed it perfectly.  Much thanks.

**Comment by GregRos** [comment]
Sure

The fix is a bit crude right now, so tell me if it causes any more problems.

Also, good luck :smile:
