### ISSUE TITLE
A very annoying thing we'll have to do: changing outdated game code inside the mod

### ISSUE THREAD

**Issue by GregRos** [GregRos/IEMod.pw#6]
Any method with the `ModifiesMember` attribute on it replaces code in the game. Sometimes, you just want to add code before/after the existing game code, in which case you can duplicate the method first using `DuplicateMember` and add a call to it, preserving the game code and smoothly integrating any changes it may undergo. (this is a feature introduced in Patchwork, so it is only present in places where I refactored the code to use it)

Usually though, you need to insert code in the middle of the method, so you have to copy the decompiled source. There's just no way around it. However, the body may have changed after a patch, and the code that was copied over the last time might be outdated, introducing hidden bugs. So we'll have to run some kind of diff between the old code and the new code.

The [old IE mod](https://bitbucket.org/Bester/poe-modding-framework) accomplished this by decompiling some of the source, tracking it in the repository in a separate branch (kind of like a sub-repository), and then merging with the old code whenever a patch came out. This gave you a diff that you could use to update the mod. I really should have duplicated this scheme, as it's very elegant and effective. I guess I will do so now, unless you have a better idea.

**Comment by tjayharvey** [comment]
Unfortunately no, I was contemplating the best way to handle this as well and didn't come up with anything useful. My feeling is that every mod will need to have a pass for this, since (from what I've seen so far) there was a lot of general cleanup done throughout the source.

**Comment by tjayharvey** [comment]
When ready, would you make issues for mods you would like me to work on for this task and assign to me? (Or give me the list and I can make the issues myself)

**Comment by GregRos** [comment]
Yeah, definitely. Sorry it's taking so long. I'm kind of distracted due to real-life issues. It's not that complicated tbh.

I was kind of thinking it might be too fragile, though, so I'm also wondering how to go about it. Do you have any ideas?

**Comment by tjayharvey** [comment]
I can't think of anything better mechanically. We could potentially have a documentation standard for "functions that we need to change the middle of" that clearly spells out what function in the source assembly it comes from and where the stock section(s) and changed section(s) begin and end, with a tag in the comments that makes searching for all such instances easier. That isn't going to help you figure out if the things you changed need to be refactored, but it could make it easier to find and update all the supposedly unchanged things.

**Comment by GregRos** [comment]
Okay, I've finally gotten it to work (had to rewrite it a bit), and it's... actually much, much better than I expected. A lot of things can be fixed with a few clicks.

I'll push the new code soon, I think. Trying to tidy up and package the code a bit better.

**Comment by GregRos** [comment]
Okay, right now I'm merging 2.0's modifications with the mod code. There are some things that will have to be changed manually, but a lot of it can be done semi-automatically. I just hope the process doesn't introduce more bugs...

We REALLY should establish some kind of standard of how to mark code that was copied from the game.

**Edit:** okay, it's done. Comment if you've noticed any new issues.

**Comment by tjayharvey** [comment]
I'd suggest we mark the methods/members. As I see it, there are three types of modifications:
1) Full replacement
2) Add at the end or beginning (usually does something and then calls the original version or vice versa)
3) Add in the middle or rewrite a portion in the middle.

3 is the kind that will have code copied from the source. However, we really need to check 1 as well because the contract/expectations of the original might have changed. If we had a function that carried out behavior A, and a previous version of the mod changed that to behavior A-modified, then if the function changed in 2.0 such that it should have behavior A+B, the mod has introduced a bug even without copying out-of-date code.

I'd suggest tagging each method with the type it is (probably just with an XML tag of <modtype> or something). Further, for type 3, which have mixed source code and changed, should have a comment before and after each section designating which it is. I'd also recommend for sections of the original code the mod cuts out (in a type 3), that we actually leave it there commented out, so that when trying to update to a later version we can understand what was intentionally removed.

**Comment by GregRos** [comment]
Sounds pretty good. If we format the comments appropriately, it would be possible to use an extension [like this](https://visualstudiogallery.msdn.microsoft.com/17c68951-7743-40bd-ad35-608706f54a92) to make sections of added/removed code stick out more, like in [this example](http://prntscr.com/8a3206). 

I have no idea what keeping sections of the old code would do to the diff tools though. They might work better, or maybe it would confuse them. I guess in the worst case, if always use consistent formatting, we could just regex remove them automatically.

**Comment by GregRos** [comment]
I'm gonna do another round of merging tomorrow and then assign some issues.

**Comment by tjayharvey** [comment]
Sounds good. I'll try to get my initial pass at fixing FastSneak in. There's a second overridden method that I commented out/haven't fixed yet but the mod works (I've been playing today with it). So I'm not sure whether it's needed or not. I figure I'll at least check it in so I have a clean branch to begin working on other mods - we can determine later if we need the other method.

Your extension looks pretty cool. I'm happy to follow any standard that helps with that kind of thing.

**Comment by GregRos** [comment]
Okay. I've done a 2nd pass of merges and I got most of them. A few things will have to be merged manually. I'll post them as issues and distribute them. There are also `/todo`s in the code about them.
