### ISSUE TITLE
2.02 beta

### ISSUE THREAD

**Issue by tjayharvey** [GregRos/IEMod.pw#66]
I'll opt into this and get started reviewing changes in a branch.

My expectation is that FastSneak may break (they are altering the movement calculating code). And given how fragile the targeting code is, I'd assume it needs to be checked.
I'll also confirm that caster-centered abilities are fixed and remove that bugfix mod if appropriate.

I don't see any other changes that look likely to cause problems. Hopefully we can have a version available a day or so after 2.02 goes fully live.

**Comment by tjayharvey** [comment]
So far:
- AttackAOE FindAoeTargets changed signature, but does not appear to have changed body (which makes the new parameter exactly useless). Updated signature.
- CommandLineRun: refactored again (easily dealt with)
- Grimoire - FindNewSpell refactored to FindNewSpells (updated)
- New dll file added - GalaxyCSharp. Updated PrepareEnvironment

Confirmed it runs with those fixes.
Confirmed Command Line still works with unlocked/added commands.
Confirmed Caster-Centered abilities bug fixed by Obsidian. Our bugfix now excluded from project.

Doing this work in the 2.02 branch, if you want to contribute or reference (not sure if you have access to 2.02 beta).

**Comment by tjayharvey** [comment]
- Confirmed that Wizard Bonus Preparation Slots still works even after Grimoire update.
- Updated Fast Sneak with very minor refactor from 2.02
- Fast Sneak still works.
- Without Fast Sneak on, runspeed/sneakspeed works as expected (with multiple characters selected, uses slowest, with individual characters, uses that characters).
- With Fast Sneak on, runspeed works as expected, but sneakspeed always uses individual character speed (rather than slowest when multiples are selected). Will try to fix, but don't consider this a serious problem.
- With both TargetTurnedEnemies and DisableFriendlyFire OFF, heals and buffs do not target enemies (but do affect charmed hostiles). Charming/Dominating an enemy renders it immune to foe-only effects, and all-type AEs hit party members. This seems to be normal, expected behavior.
- With TargetTurnedEnmies off and DisableFriendlyFire ON, heals and buffs do not target enemies (but do affect charmed/dominated hostiles). Charming/Dominating an enemy renders it immune to all AE, and no hostile AE will hit a party member. This looks okay too.
- With TargetTurnedEnemies ON and DisableFriendlyFire OFF, heals and buffs do not target enemies, not even charmed/dominated ones. Charming/Dominating an enemy still keeps it vulnerable to foe-only effects, and all-type AEs hit party members. This looks good.
- With both TargetTurnedEnemies and DisableFriendlyFire ON, heals and buffs do not target enemies, even charmed/dominated ones. Charming/Dominating an enemy still keeps it vulnerable to foe-only effects, and no friendly casted AEs will hit party members. This also looks great. Also, in this last test, a charmed hostile priest cast Devotions for the Faithful on the entire area (buffs friends, debuffs foes). It acquired my party, the caster, and the non-charmed members of the caster's party as targets. It treated the caster and the caster's original faction as hostile and my party as friendly. This seems like reasonable behavior for charmed buffers, except I'm not sure they should be debuffing themselves! It's probably harder to fix this then worth it.

**Comment by tjayharvey** [comment]
I can't figure out why FastSneak doesn't synchronize two fast-sneaking members with different speeds. I think it's because all the calculations on speed in FastSneak don't matter at all. I think all that routine is REALLY doing is determine whether the Mover is using Walk speed or Run speed. Let's say Kana is wearing the Arrow-breaker armor that increases speed (he is in my game, which makes testing this super easy). If he's fast sneaking by himself, it sets his desired speed to 5. If he's fast sneaking with Eder (no bonus), it sets his desired speed to 4. Regardless, he still moves at speed 5! 

This will probably require modding Mover to fix (best bet is probably analyzing where the bugfix in 2.02 that fixed this for normal movers is located, since that's almost certainly the spot we also need to deal with Fast Sneak). I don't feel this is important enough to block anything, so I'm going to make it as an issue and deal with it later.

Going to release a beta version of IEMod to go with the current beta patch on Steam to try to get some early feedback. At this point it feels stable enough to get other feedback. Will make sure it has a very large disclaimer.

**Comment by tjayharvey** [comment]
Er, the current patch is now 2.02 already! Which makes it even more important to release a beta IEMod. It should be up now.

**Comment by SonicZentropy** [comment]
Any chance of getting your 2.02 branch pulled into this repo, or at least mentioned in the Readme?  I just spent a while fixing all of this stuff locally because I didn't check this Issue and see you'd already fixed it all in a branch on your fork.  Doesn't need to be merged with this master I suppose, but it'd be nice to have your updated version in a branch at least!

**Comment by sztrzask** [comment]
So... how about 2.03?

**Comment by tjayharvey** [comment]
Working on 3.01 version now - Greg had made a 2.03 compatable version but didn't close this issue.
