### ISSUE TITLE
Cipher Base Focus Mod

### ISSUE THREAD

**Issue by tjayharvey** [GregRos/IEMod.pw#7]
Working on a mod to give the player to choose (in the Options menu) the choice between several starting focus values for the Cipher. Planned options are 0, 1/4 max, 1/2 max, 3/4 max, and max (though max is really going to be ridiculously overpowered). Don't personally feel that Cipher's front-loading was really that bad at the high end when Druid/Wizard/Priest gets to cast all their encounter-based spells, so I personally wanted to revert back to 1/2 max. There was also a request on the Nexus page for IEMod to add this, and it fits alongside the Spell Per Day mod.

I've got the effect working (just hardwired to 1/2 max at the moment), so really it's just a matter of adding the options and hooking up a dropdown for it.

Obviously lower priority than fixing the existing stuff, but wanted to post that I'm working on it.

**Comment by GregRos** [comment]
Cool man :) 

Yup, it's a pretty popular request. Feel free the add the dropdown/options.

**Comment by tjayharvey** [comment]
Leaving this open until I have a chance to test what Soul Whip does with max base focus. If it misbehaves, I may just eliminate that option rather than try to track it down.

**Comment by tjayharvey** [comment]
Tested. Soul Whip does not activate at start of battle with "Max Focus" selected as an option, but does activate as soon as you spend any focus. Seems fine, so I'm going to close this issue.
