### ISSUE TITLE
3.07

### ISSUE THREAD

**Issue by ALIENQuake** [GregRos/IEMod.pw#98]
Hi,

Pillars of Eternity - Definitive Edition is out and current patch version is 3.07.

@Alakabon I don't want to nag you since I'm not sure if you are still playing with it but in case you would like someone for testing, you have my axe :)

**Comment by ALIENQuake** [comment]
@GregRos Hi, Pillars of Eternity II Deadfire is coming! Any chances for update to the 'final' Pillars of Eternity Patch 3.07.1318 ? Or providing instruction how to do it?

**Comment by BluesKutya** [comment]
I have updated some files and build a compatible, (and smoke-tested) version base on my fork.
(PoE "Definitive Edition" 3.7.0.1280 PX1 PX2 PX4)

**Comment by ALIENQuake** [comment]
@BluesKutya Thanks! I've made some meaningless cleanups of the project, care to accept PR?

**Comment by biship** [comment]
I cloned the repo, extracted patchwork into the empty patchwork folder & set the solution to PrepareEnvironment.

Cecil shows errors: 2>\IEMod.pw\Patchwork\cecil-0.9.6\symbols\mdb\Mono.CompilerServices.SymbolWriter\SymbolWriterImpl.cs(41,33,41,46): error CS0122: 'ISymbolWriter' is inaccessible due to its protection level

Pillars of Eternity & Patchwork won't compile until C ecil does.

**Comment by ALIENQuake** [comment]
@biship You don't need to use PrepareEnvironment, just use Debug.

P.S. The Visual Studio solution configuration for this project is a mess...

**Comment by biship** [comment]
Thanks, but even with Debug it still doesn't build. Any ideas?
https://pastebin.com/7wUm7Ucr

PoEGameInfo.cs  has:
Error	CS0115	'PoEAppInfoFactory.CreateInfo(DirectoryInfo)': no suitable method found to override	PoEGameInfo	I:\Code\Games\IEMod.pw\PoEGameInfo\PoEGameInfo.cs	14	Active
and complains about the AppInfo, AppInoFactory & Patchwork namespaces.

**Comment by ALIENQuake** [comment]
@biship Yep, that's the mess with solution configuration, wait till end of the weekend and I will post a solution which will at least build without problems.

**Comment by biship** [comment]
Thank you!
